### ISSUE TITLE
Update command does not apply changes

### ISSUE THREAD

**Issue by timthelion** [bitswan-space/bitswan-gitops#43]
Docker compose file is updated but containers aren't actually restarted.

```
[root@nixos:~]# ./bitswan-gitops-cli update <workspace-name>
Updating Gitops: ...
Ensuring examples are up to date...
Updating BitSwan repository at /root/.config/bitswan/bitswan-src/bitswan-src
Already up to date.
Repository updated successfully
Examples are up to date!
Updating Docker images and docker-compose file...
Restarting services...

[root@nixos:~]# docker ps
ca12949f20e0   bitswan/gitops:2025-14065072711-git-161f667                                                 "bitswan-gitops-serv…"   27 hours ago        Up 27 hours        8079/tcp                                                                                                                       ...-site-gitops-1

[root@nixos:~]# cat .config/bitswan/workspaces/.../deployment/docker-compose.yml
networks:
  bitswan_network:
    external: true
services:
  ...:
    environment:
      - BITSWAN_GITOPS_DIR=/gitops
      - BITSWAN_GITOPS_DIR_HOST=/root/.config/bitswan/workspaces/...
      - BITSWAN_GITOPS_ID=...
      - BITSWAN_GITOPS_SECRET=...
      - BITSWAN_GITOPS_DOMAIN=...
      - HOST_PATH=$PATH
      - HOST_HOME=$HOME
      - HOST_USER=$USER
    image: bitswan/gitops:2025-14111047928-git-6c4cb97
    networks:
      - bitswan_network
    pid: host
    privileged: true
    restart: always
    volumes:
      - /root/.config/bitswan/workspaces/.../gitops:/gitops/gitops
      - /root/.config/bitswan/workspaces/.../secrets:/gitops/secrets
      - /root/.ssh:/root/.ssh
      - /var/run/docker.sock:/var/run/docker.sock
  bitswan-editor-...:
    environment:
      - BITSWAN_DEPLOY_URL=http://...:8079
      - BITSWAN_DEPLOY_SECRET=...
      - BITSWAN_GITOPS_DIR=/home/coder/workspace
    image: bitswan/bitswan-editor:2025-14104371955-git-cf25b72
    networks:
      - bitswan_network
    restart: always
    volumes:
      - /root/.config/bitswan/workspaces/.../workspace:/home/coder/workspace/workspace
      - /root/.config/bitswan/workspaces/.../secrets:/home/coder/workspace/secrets
      - /root/.config/bitswan/workspaces/.../codeserver-config:/home/coder/.config/code-server/
      - /root/.config/bitswan/bitswan-src/examples:/home/coder/workspace/examples:ro
      - /root/.ssh:/home/coder/.ssh
version: "3.8"
volumes:
  bitswan-editor-data: null

[root@nixos:~]#
```
